services:
  msorder:
    build: .
    container_name: msorder
    depends_on:
      - db
    networks:
      - microservices-network

  db:
    image: postgres:15-alpine
    container_name: postgres-msorder
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_order
    ports:
      - "5433:5432" # continua mapeando para acessar do host na 5433
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true

volumes:
  postgres_order_data:
