services:
  msorder:
    build: .
    container_name: msorder
    depends_on:
      - db
      - rabbitmq
    networks:
      - microservices-network

  db:
    image: postgres:15-alpine
    container_name: postgres-msorder
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_order
    ports:
      - "5433:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # porta de conexão da aplicação
      - "15672:15672" # porta do painel de administração (http://localhost:15672)
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true

volumes:
  postgres_order_data:
